**Part 1 – Implement Basic Data Structures using Numpy, Pandas**

In [9]:
import numpy as np
s=[]
n=int(input())
for i in range(n):
  a=int(input())
  s.append(a)
print(s)
b=np.array(s)
print(b)
type(s)
type(b)

3
1
0
2
[1, 0, 2]
[1 0 2]


numpy.ndarray

In [16]:
import numpy as np
list1=[1,2,3,4,5,6]
print(type(list1))
arr1=np.array(list1)
print(list1)
print(arr1)
print(type(arr1))

<class 'list'>
[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [17]:

A = [2, 4, 6, 8]
B = [1, 2, 3, 4]
C = [a * b for a, b in zip(A,B)]
print("Multiplication result:", C)

D = [a / b for a, b in zip(A,B)]
print("Division result:", D)

# Perform exponentiation (power of)
E= [a ** b for a, b in zip(A,B)]
print("Exponentiation result:", E)


Multiplication result: [2, 8, 18, 32]
Division result: [2.0, 2.0, 2.0, 2.0]
Exponentiation result: [2, 16, 216, 4096]


In [18]:
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result_array = array1 + array2
text_output = f"Addition of Two:\narray1 + array2\n{array1} + {array2} = {result_array}"
print(text_output)


Addition of Two:
array1 + array2
[1 2 3] + [4 5 6] = [5 7 9]


In [22]:
import numpy as np
A = np.array([1, 2, 3, 4, 5])
sin_result =np.sin(A)
log_result = np.log(A)
log2_result = np.log2(A)
exp_result = np.exp(A)
print("sin:", sin_result)
print("log:", log_result)
print("log2:", log2_result)
print("exp:", exp_result)

sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
log2: [0.         1.         1.5849625  2.         2.32192809]
exp: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
